# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-15 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcategory',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыт?'),
        ),
    ]
