# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcategory',
            name='title',
            field=models.CharField(max_length=14, verbose_name='Название категории'),
        ),
    ]
