# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_category', '0002_auto_20170502_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcategory',
            name='slug',
            field=models.CharField(max_length=255, verbose_name='Название на транслите'),
        ),
        migrations.AlterField(
            model_name='globalcategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
    ]
