# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('category', '0001_initial'),
        ('global_category', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(blank=True, max_length=225, null=True, verbose_name='Н1 заголовок')),
                ('title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Мета название')),
                ('description', models.TextField(blank=True, max_length=140, null=True, verbose_name='Мета описание')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова')),
                ('seo_text', models.TextField(blank=True, null=True, verbose_name='Сео текст')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='УРЛ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('global_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_category.GlobalCategory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
            options={
                'verbose_name': 'Метаданные',
                'verbose_name_plural': 'Метаданные',
            },
        ),
    ]
