# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_metadata_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='product',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='shop',
        ),
    ]
