# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/icons/', verbose_name='Иконка категории'),
        ),
    ]
