# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20170426_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcategory',
            name='icon',
            field=models.ImageField(default=None, upload_to='category/icons'),
        ),
    ]
