# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20170706_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='category/icons/', verbose_name='Иконка категории'),
        ),
    ]
