# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20170427_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='section',
        ),
        migrations.DeleteModel(
            name='GlobalCategory',
        ),
    ]
