# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_category', '0001_initial'),
        ('category', '0005_auto_20170429_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_category.GlobalCategory', verbose_name='Раздел'),
        ),
    ]
