# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sociallinks_icon'),
        ('category', '0006_category_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='Магазин'),
        ),
    ]
