# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20170501_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
