# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Скидка')),
                ('currency', models.CharField(max_length=255, null=True, verbose_name='Валюта')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('delivery_type', models.CharField(max_length=255, null=True, verbose_name='Вид доставки')),
                ('delivery_cost', models.FloatField(null=True, verbose_name='Стоимость доставки')),
                ('delivery_currency', models.CharField(max_length=255, null=True, verbose_name='Валюта доставки')),
                ('in_stock', models.BooleanField(default=False, verbose_name='В наличии?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='Название категории')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='Название магазина')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
