# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 09:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Избранные продукты',
                'verbose_name': 'Избранный продукт',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название на транслите')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена')),
                ('sell_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество продаж')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('currency', models.CharField(default='сом', max_length=255, null=True, verbose_name='Валюта')),
                ('delivery_type', models.CharField(choices=[('self', 'Самовывоз'), ('paid', 'Платная доставка'), ('free', 'Бесплатная доставка')], default='self', max_length=255, verbose_name='Вид доставки')),
                ('delivery_cost', models.FloatField(blank=True, default=0, null=True, verbose_name='Стоимость доставки')),
                ('availability', models.CharField(choices=[('available', 'В наличии'), ('waiting', 'Ожидается'), ('not_available', 'Нет в наличии')], default='available', max_length=100, verbose_name='Наличие')),
                ('short_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Короткое описание товара до 300 символов')),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='Название категории')),
            ],
            options={
                'verbose_name_plural': 'Продукты',
                'ordering': ('-created_at',),
                'verbose_name': 'Продукт',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/image')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'Изображения товара',
                'verbose_name': 'Изображение товара',
            },
        ),
    ]
