# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170803_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, choices=[('available', 'В наличии'), ('waiting', 'Ожидается'), ('not_available', 'Нет в наличии')], default='available', max_length=100, null=True, verbose_name='Наличие'),
        ),
    ]
