# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20170427_1901'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('week_best', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='В наличии?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
