# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_partner_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_avatar',
            field=models.BooleanField(default=False, verbose_name='Аватар продукта'),
        ),
    ]
