# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
