# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productimage_thumb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='thumb_image',
            field=models.ImageField(max_length=230, null=True, upload_to='products/image/thumb'),
        ),
    ]
