# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20170427_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='сом', max_length=255, null=True, verbose_name='Валюта'),
        ),
    ]
