# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20170822_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета ключевые слова'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_text',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Текст'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumb_image',
            field=models.ImageField(max_length=230, null=True, upload_to='products/thumb'),
        ),
    ]
