# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20170427_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(choices=[('self', 'Самовывоз'), ('paid', 'Платная'), ('free', 'Бесплатная')], default='self', max_length=255, verbose_name='Вид доставки'),
        ),
    ]
