# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_auto_20170427_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Product')),
            ],
            bases=('product.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(choices=[('self', 'Самовывоз'), ('paid', 'Платная доставка'), ('free', 'Бесплатная доставка')], default='self', max_length=255, verbose_name='Вид доставки'),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='product.Product'),
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
