# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20170824_1821'),
        ('product', '0011_auto_20170825_1743'),
    ]

    operations = [
    ]
