# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20170427_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favoriteproduct',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='favoriteproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteProduct',
        ),
    ]
