# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_merge_20170828_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=300, upload_to='products/image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumb_image',
            field=models.ImageField(max_length=300, null=True, upload_to='products/thumb'),
        ),
    ]
