# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-04 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20170906_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('som', 'Сом'), ('dollar', '$')], default='som', max_length=255, null=True, verbose_name='Валюта'),
        ),
    ]
