# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-12 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20171004_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(choices=[('dollar', '$')], max_length=20, verbose_name='Тип валюты')),
                ('exchange_rate', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Курс')),
            ],
            options={
                'verbose_name_plural': 'Курс валют',
            },
        ),
    ]
