# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20171112_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Курс'),
        ),
    ]
