# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20170428_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_stock',
            new_name='availability',
        ),
    ]
