# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20170429_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('self', 'Самовывоз'), ('paid', 'Платная доставка'), ('free', 'Бесплатная доставка')], max_length=100, verbose_name='Наличие'),
        ),
    ]
