# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20170429_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('available', 'Самовывоз'), ('waiting', 'Платная доставка'), ('not_available', 'Бесплатная доставка')], default='not_available', max_length=100, verbose_name='Наличие'),
        ),
    ]
