# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20170429_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('available', 'В наличии'), ('waiting', 'Ожидается'), ('not_available', 'Нет в наличии')], default='not_available', max_length=100, verbose_name='Наличие'),
        ),
    ]
