# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20170429_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='product.Product'),
        ),
    ]
