# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_product_delivery_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_cost',
            field=models.FloatField(default=0, verbose_name='Стоимость доставки'),
        ),
    ]
