# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20170504_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('available', 'В наличии'), ('waiting', 'Ожидается'), ('not_available', 'Нет в наличии')], default='available', max_length=100, verbose_name='Наличие'),
        ),
    ]
