# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20170523_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Стоимость доставки'),
        ),
    ]
