# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20170523_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sell_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество продаж'),
        ),
    ]
