# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 11:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20170523_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Короткое описание товара до 300 символов'),
        ),
    ]
