# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20170524_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
