# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20170524_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='media',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
