# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20170526_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='products',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
