# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_values_products'),
        ('product', '0034_auto_20170527_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='values',
            field=models.ManyToManyField(blank=True, to='properties.Values', verbose_name='Характеристики'),
        ),
    ]
