# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20170610_1155'),
        ('product', '0038_auto_20170610_1424'),
    ]

    operations = [
    ]
