# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20170426_2040'),
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filters',
            name='category',
        ),
        migrations.AddField(
            model_name='filters',
            name='category',
            field=models.ManyToManyField(to='category.Category', verbose_name='Категория'),
        ),
    ]
