# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Продукт в корзине', 'verbose_name_plural': 'Продукты в корзине'},
        ),
    ]
