# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20170501_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='line_item_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
