# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередь')),
                ('title', models.CharField(max_length=255, verbose_name='Название параметра')),
                ('slug', models.CharField(max_length=255, null=True, verbose_name='Slug')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('category', models.ManyToManyField(blank=True, to='category.Category', verbose_name='Категория')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Properties', verbose_name='Родительский параметр')),
            ],
            options={
                'verbose_name_plural': 'Свойства',
                'verbose_name': 'Свойство',
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередь')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('products', models.ManyToManyField(blank=True, to='product.Product')),
                ('properties', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Properties', verbose_name='Параметр')),
            ],
            options={
                'verbose_name_plural': 'Значения',
                'verbose_name': 'Значение',
            },
        ),
    ]
