# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Очередь')),
                ('title', models.CharField(max_length=255, verbose_name='Название параметра')),
                ('slug', models.CharField(max_length=255, null=True, verbose_name='Slug')),
                ('category', models.ManyToManyField(to='category.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Очередь')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Properties', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
            },
        ),
    ]
