# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20170504_1228'),
        ('category', '0011_auto_20170501_1813'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='category',
        ),
        migrations.AddField(
            model_name='values',
            name='products',
            field=models.ManyToManyField(to='product.Product', verbose_name='Товары'),
        ),
        migrations.RemoveField(
            model_name='properties',
            name='category',
        ),
        migrations.AddField(
            model_name='properties',
            name='category',
            field=models.ManyToManyField(to='category.Category', verbose_name='Категория'),
        ),
    ]
