# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_values'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
