# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='help_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вспомогательный текст'),
        ),
    ]
