# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_values_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='parent',
            field=mptt.fields.TreeForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Properties', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='properties',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='properties',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
