# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20170522_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='slug',
            field=models.CharField(max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
