# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_values_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name': 'Свойство', 'verbose_name_plural': 'Свойства'},
        ),
    ]
