# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20170610_1353'),
        ('properties', '0005_auto_20170610_1155'),
        ('properties', '0005_auto_20170609_1912'),
    ]

    operations = [
    ]
