# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20170705_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
