# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 20:28
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20170705_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Properties', verbose_name='Родительский параметр'),
        ),
    ]
