# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170628_2011'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(related_name='sub_shops', to='shop.Shop', verbose_name='Подписка на магазины'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('all', 'Все'), ('only_actions', 'Акции'), ('only_products', 'Товары')], default='all', max_length=50, verbose_name='Тип подписки'),
        ),
    ]
