# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170628_2011'),
        ('users', '0002_auto_20170705_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('all', 'Все'), ('only_actions', 'Акции'), ('only_products', 'Товары')], default='all', max_length=50, verbose_name='Тип подписки')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_shops', to='shop.Shop', verbose_name='Подписка на магазины')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
