# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.GlobalCategory', verbose_name='Раздел'),
        ),
    ]
