# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20170506_1452'),
        ('order', '0002_simpleorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
            preserve_default=False,
        ),
    ]
