# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170801_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Удален магазином'),
        ),
    ]
