# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_simpleorder_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Не скрыт'),
        ),
    ]
