# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_simpleorder_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleorder',
            name='product',
        ),
    ]
