# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-04 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20171029_1844'),
        ('order', '0004_auto_20170817_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='confirm_shops',
            field=models.ManyToManyField(to='shop.Shop', verbose_name='Подтвержденные магазины'),
        ),
    ]
