# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20170527_1343'),
        ('order', '0004_remove_simpleorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='product.Product'),
        ),
    ]
