# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_simpleorder_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleorder',
            name='products',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
