# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-03 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20170603_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='simpleorder',
            name='cart',
        ),
    ]
