# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20171105_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Новый'), ('processed', 'Обработан')], default='created', max_length=120),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='status',
            field=models.CharField(choices=[('created', 'Новый'), ('processed', 'Обработан')], default='created', max_length=120),
        ),
    ]
