# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20170603_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleorder',
            name='updated',
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Публиковать'),
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='simpleorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
    ]
