# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 09:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название баннера')),
                ('image', models.ImageField(upload_to='images/shop/banners/', verbose_name='Изображение банера')),
            ],
            options={
                'verbose_name_plural': 'Баннеры магазинов',
                'verbose_name': 'Баннер магазина',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота')),
                ('monday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Понедельник')),
                ('tuesday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вторник')),
                ('wednesday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Среда')),
                ('thursday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Четверг')),
                ('friday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пятница')),
                ('saturday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Суббота')),
                ('sunday', models.CharField(blank=True, max_length=255, null=True, verbose_name='Воскресенье')),
                ('round_the_clock', models.BooleanField(default=False, verbose_name='Круглосуточно')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
                'verbose_name': 'Контакт',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('mall', 'Торговый центр'), ('market', 'Рынок')], max_length=255, verbose_name='Тип торговой точки')),
            ],
            options={
                'verbose_name_plural': 'Торговые точки',
                'verbose_name': 'Торговая точка',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('title', models.CharField(max_length=50, verbose_name='Название акции')),
                ('short_description', models.TextField(max_length=155, verbose_name='Короткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('discount', models.IntegerField(verbose_name='Скидка')),
                ('image', models.ImageField(upload_to='shops/sales', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Акции',
                'ordering': ['-created_at'],
                'verbose_name': 'Акция',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('title', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('slug', models.CharField(max_length=32, unique=True, verbose_name='Название на транслите')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail магазина')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Короткое описание магазина')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Полное описание магазина')),
                ('logo', models.ImageField(default='/default.jpg', upload_to='images/shop/logo/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name_plural': 'Магазины',
                'verbose_name': 'Магазин',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('vk', models.CharField(blank=True, max_length=255, null=True, verbose_name='VK')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
            options={
                'verbose_name_plural': 'Социальные ссылки',
                'verbose_name': 'Социальная ссылка',
            },
        ),
    ]
