# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название баннера')),
                ('image', models.ImageField(upload_to='images/shop/banners/', verbose_name='Изображение банера')),
            ],
            options={
                'verbose_name': 'Баннер магазина',
                'verbose_name_plural': 'Баннеры магазинов',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('slug', models.CharField(max_length=32, verbose_name='Название на транслите')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail магазина')),
                ('short_decription', models.TextField(max_length=300, verbose_name='Короткое описание магазина')),
                ('description', models.TextField(max_length=1500, verbose_name='Полное описание магазина')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('updated_ad', models.DateTimeField(auto_now_add=True, verbose_name='Обновленно')),
                ('logo', models.ImageField(null=True, upload_to='images/shop/logo/', verbose_name='Логотип')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Banners')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
