# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название баннера')),
                ('image', models.ImageField(upload_to='images/shop/banners/', verbose_name='Изображение банера')),
            ],
            options={
                'verbose_name': 'Баннер магазина',
                'verbose_name_plural': 'Баннеры магазинов',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('title', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('slug', models.CharField(max_length=32, unique=True, verbose_name='Название на транслите')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail магазина')),
                ('short_description', models.TextField(max_length=300, verbose_name='Короткое описание магазина')),
                ('description', models.TextField(max_length=1500, verbose_name='Полное описание магазина')),
                ('logo', models.ImageField(null=True, upload_to='images/shop/logo/', verbose_name='Логотип')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Администратор магазина')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('vk', models.CharField(blank=True, max_length=255, null=True, verbose_name='VK')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
            options={
                'verbose_name': 'Социальная ссылка',
                'verbose_name_plural': 'Социальные ссылки',
            },
        ),
        migrations.AddField(
            model_name='banners',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
    ]
