# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170801_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название магазина'),
        ),
    ]
