# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='banner',
        ),
        migrations.AddField(
            model_name='banners',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
    ]
