# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170614_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('contact_type', models.CharField(choices=[('phone', 'Номер телефона'), ('address', 'Адрес')], max_length=20, verbose_name='Тип контактных данных')),
                ('contact_value', models.CharField(blank=True, max_length=700, null=True, verbose_name='Текст данных')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
                'verbose_name': 'Контакт',
            },
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(default='/default.jpg', upload_to='images/shop/logo/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='Магазин'),
        ),
    ]
