# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170801_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('mall', 'ТЦ'), ('market', 'Рынок')], max_length=255, verbose_name='Тип торговой точки'),
        ),
    ]
