# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_phone'),
        ('shop', '0005_auto_20170429_1414'),
    ]

    operations = [
    ]
