# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170818_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('title',), 'verbose_name': 'Торговая точка', 'verbose_name_plural': 'Торговые точки'},
        ),
    ]
