# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170821_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета описание'),
        ),
        migrations.AddField(
            model_name='shop',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета ключевые слова'),
        ),
        migrations.AddField(
            model_name='shop',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Мета заголовок'),
        ),
        migrations.AddField(
            model_name='shop',
            name='seo_text',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Текст'),
        ),
    ]
