# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='place',
            field=models.ManyToManyField(blank=True, to='shop.Place', verbose_name='Торговые точки'),
        ),
    ]
