# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_20170429_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на страницу соц.сети')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop')),
            ],
            options={
                'verbose_name_plural': 'Социальные ссылки',
                'verbose_name': 'Социальная ссылка',
            },
        ),
        migrations.RenameField(
            model_name='banners',
            old_name='banner',
            new_name='shop',
        ),
    ]
