# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sociallinks_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название на транслите'),
        ),
    ]
