# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170922_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/shop/logo/', verbose_name='Логотип'),
        ),
    ]
