# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 07:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170627_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('title', models.CharField(max_length=50, verbose_name='Название акции')),
                ('short_description', models.CharField(max_length=155, verbose_name='Короткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('discount', models.IntegerField(verbose_name='Скидка')),
                ('image', models.ImageField(upload_to='shops/sales', verbose_name='Изображение')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name_plural': 'Акции',
                'verbose_name': 'Акция',
            },
        ),
    ]
