# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-29 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20170922_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='shops/sales/thumb'),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/shop/logo/thumb/'),
        ),
    ]
