# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170526_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
    ]
