# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170628_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='short_description',
            field=models.TextField(max_length=155, verbose_name='Короткое описание'),
        ),
    ]
