# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20170705_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-created_at'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
