# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170527_1320'),
        ('shop', '0012_auto_20170526_2159'),
    ]

    operations = [
    ]
