# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 09:08
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20170710_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='work_time',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Время работы'),
        ),
    ]

