# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_contacts_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='work_time',
            field=models.TextField(blank=True, null=True, verbose_name='График работы'),
        ),
    ]
