# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_contacts_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
