# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_contacts_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='location',
        ),
        migrations.AddField(
            model_name='contacts',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Широта'),
        ),
    ]
