# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20170713_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Долгота'),
        ),
    ]
