# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20170713_1747'),
        ('shop', '0019_shop_counter'),
    ]

    operations = [
    ]
