# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_merge_20170717_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='friday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='monday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='saturday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='sunday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='thursday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='tuesday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Понедельник'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='wednesday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Понедельник'),
        ),
    ]
