# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20170721_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='work_time',
        ),
    ]
