# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20170724_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание магазина'),
        ),
    ]
