# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_remove_product_values'),
        ('shop', '0005_auto_20170621_1338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('stars', models.CharField(blank=True, choices=[('*', 'очень плохо'), ('**', 'плохо'), ('***', 'удовлетворительно'), ('****', 'хорошо'), ('*****', 'отлично')], max_length=100, null=True, verbose_name='Звездочки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Отзывы товара',
                'verbose_name': 'Отзыв товара',
            },
        ),
        migrations.CreateModel(
            name='ShopReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('stars', models.CharField(blank=True, choices=[('*', 'очень плохо'), ('**', 'плохо'), ('***', 'удовлетворительно'), ('****', 'хорошо'), ('*****', 'отлично')], max_length=100, null=True, verbose_name='Звездочки')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Отзывы магазинов',
                'verbose_name': 'Отзыв магазина',
            },
        ),
    ]
