# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-01 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('stars', models.CharField(blank=True, choices=[('*', 'очень плохо'), ('**', 'плохо'), ('***', 'удовлетворительно'), ('****', 'хорошо'), ('*****', 'отлично')], max_length=100, null=True, verbose_name='Звездочки')),
            ],
            options={
                'verbose_name_plural': 'Отзывы товара',
                'verbose_name': 'Отзыв товара',
            },
        ),
        migrations.CreateModel(
            name='ShopReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('stars', models.CharField(blank=True, choices=[('*', 'очень плохо'), ('**', 'плохо'), ('***', 'удовлетворительно'), ('****', 'хорошо'), ('*****', 'отлично')], max_length=100, null=True, verbose_name='Звездочки')),
            ],
            options={
                'verbose_name_plural': 'Отзывы магазинов',
                'verbose_name': 'Отзыв магазина',
            },
        ),
    ]
