# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('title', models.CharField(max_length=400, verbose_name='Название блока')),
                ('url', models.CharField(max_length=450, verbose_name='Урл')),
                ('image', models.ImageField(upload_to='images/index/')),
                ('column', models.CharField(choices=[('first_col', 'Первая колонка'), ('second_col', 'Вторая колонка'), ('third_col', 'Третья колонка')], max_length=50, verbose_name='Колонка')),
                ('row', models.PositiveSmallIntegerField(verbose_name='Ряд')),
            ],
            options={
                'verbose_name': 'Блок на главной странице',
                'verbose_name_plural': 'Блоки на главной странице',
            },
        ),
    ]
