# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexblocks',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название блока'),
        ),
    ]
