# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-19 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20171018_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumIndexBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Наименование блока')),
                ('url', models.CharField(max_length=450, verbose_name='Ссылка')),
                ('block_type', models.CharField(choices=[('big_up_block', 'Большой верхний блок'), ('big_down_block', 'Большой нижний блок'), ('up_left_corner_1', 'Верхняя левая сторона верхний блок'), ('up_left_corner_2', 'Верхняя левая сторона нижний блок'), ('up_right_corner_1', 'Верхняя правая сторона верхний блок'), ('up_right_corner_2', 'Верхняя правая сторона нижний блок'), ('down_right_corner_1', 'Нижняя правая сторона верхний блок'), ('down_right_corner_2', 'Нижняя правая сторона нижний блок')], max_length=100, unique=True, verbose_name='Тип блока')),
                ('image', models.ImageField(upload_to='images/index/premium/', verbose_name='Изображение блока')),
            ],
            options={
                'verbose_name': 'Премиум блок',
                'verbose_name_plural': 'Премиум блоки на главной странице',
            },
        ),
    ]
