# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-19 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_premiumindexblocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('published', models.BooleanField(default=True, verbose_name='Публиковать')),
                ('image', models.ImageField(upload_to='images/index/banners/', verbose_name='Изображение банера')),
                ('banner_type', models.CharField(choices=[('offer', 'Рекламное предложение'), ('slider', 'Банер на слайдер')], max_length=50, verbose_name='Тип банера')),
                ('url', models.CharField(max_length=450, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name_plural': 'Банера на главной странице',
                'verbose_name': 'Банер',
            },
        ),
    ]
