# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-12 08:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
    ]
